name: Check for Localhost URLs
on: [pull_request]

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check for localhost URLs
      run: |
        if grep -r "localhost:3000" --include="*.js" --include="*.jsx" --include="*.ts" --include="*.tsx" --include="*.json" .; then
          echo "::error::Found localhost URLs! Please replace them with the production URL before merging."
          exit 1
        fi