name: Replace Localhost URLs

on: 
  pull_request:
    branches:
      - main  # Ou a branch principal que você usa

jobs:
  replace-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace Localhost URLs
        run: |
          find . -type f \( -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" -o -name "*.json" \) \
            -exec sed -i 's|http://localhost:3000|https://apolopi.onrender.com|g' {} +
          find . -type f \( -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" -o -name "*.json" \) \
            -exec sed -i 's|localhost:3000|https://apolopi.onrender.com|g' {} +

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git diff --staged --quiet || git commit -m "Replace localhost URLs with https://apolopi.onrender.com"
          git push

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: url-replacements
          path: .