name: Replace Localhost URLs
on: pull_request

jobs:
  replace-urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Replace URLs
      run: |
        find . -type f \( -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" -o -name "*.json" \) \
          -exec sed -i 's|http://localhost:3000|https://mathlingo.onrender.com|g' {} +
        find . -type f \( -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" -o -name "*.json" \) \
          -exec sed -i 's|localhost:3000|https://mathlingo.onrender.com|g' {} +
    - name: Create Artifact
      uses: actions/upload-artifact@v3
      with:
        name: url-replacements
        path: .