name: Check for Localhost URLs

on: 
  pull_request:
    branches:
      - main 

jobs:
  check-localhost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Search for 'localhost' references
        run: |
          echo "🔍 Procurando por URLs com 'localhost'..."
          MATCHES=$(grep -rnw '.' -e 'localhost:3000' --include=\*.{js,jsx,ts,tsx,json} || true)

          if [ -n "$MATCHES" ]; then
            echo "🚨 Foram encontradas referências a 'localhost:3000':"
            echo "$MATCHES"
            echo "❌ Por favor, substitua 'localhost:3000' por 'https://apolopi.onrender.com' antes de fazer o pull request."
            exit 1
          else
            echo "✅ Nenhuma referência a 'localhost:3000' encontrada."
          fi
